# Generated by Django 2.2 on 2020-05-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Email Address')),
                ('phone', models.IntegerField(max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='authorImages/')),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogImages/')),
                ('posted', models.DateTimeField(auto_now_add=True, verbose_name='Posted On')),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Health', 'Health'), ('International', 'International'), ('Politics', 'Politics'), ('Society', 'Society'), ('Economics', 'Economics'), ('Education', 'Education'), ('Tourism', 'Tourism'), ('Development', 'Development'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Entertainment', 'Entertainment')], max_length=20)),
                ('author', models.ForeignKey(default=1, null=1, on_delete=django.db.models.deletion.SET_NULL, to='home.Author')),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-posted'],
            },
        ),
    ]
