# Generated by Django 2.2 on 2020-05-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='blogImages/'),
        ),
    ]
