# Generated by Django 2.2 on 2020-05-28 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='links',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.AuthorFollowLinks'),
        ),
    ]
