# Generated by Django 2.2 on 2020-05-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogpost_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Posted On'),
        ),
    ]
