# Generated by Django 2.2 on 2020-05-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Message from Customers',
            },
        ),
        migrations.AlterField(
            model_name='search',
            name='user',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
