# Generated by Django 2.2 on 2020-05-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200525_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Advertisement Name')),
                ('company', models.CharField(max_length=50, verbose_name='Advertisement Company')),
                ('type', models.CharField(choices=[('Main', 'Main'), ('Side', 'Side')], max_length=10)),
                ('image', models.ImageField(upload_to='advertisementImages')),
            ],
            options={
                'verbose_name_plural': 'Advertisement Images',
            },
        ),
    ]
