# Generated by Django 2.2 on 2020-05-30 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200530_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-updated', '-posted'], 'verbose_name_plural': 'Blog Posts'},
        ),
    ]
