# Generated by Django 2.2 on 2020-05-26 05:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='posted',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 5, 26, 5, 17, 7, 695071, tzinfo=utc), verbose_name='Posted On'),
            preserve_default=False,
        ),
    ]
