# Generated by Django 2.2 on 2020-05-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200526_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimages',
            options={'verbose_name_plural': 'Post Images'},
        ),
    ]
