# Generated by Django 2.2 on 2020-05-27 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200526_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriber', models.EmailField(max_length=30, verbose_name='Subscriber Email')),
                ('subscribed', models.DateTimeField(auto_now_add=True, verbose_name='Sunscribed On')),
            ],
            options={
                'verbose_name_plural': 'Subscribers List',
                'ordering': ['-subscribed'],
            },
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Searches'},
        ),
    ]
