# Generated by Django 2.2 on 2020-05-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200527_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Subscriber Email'),
        ),
    ]
