# Generated by Django 2.2 on 2020-05-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200527_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='False', max_length=5),
        ),
    ]
